# Generated by Django 5.2.1 on 2026-08-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us Settings (Create only one record)', max_length=100)),
                ('data', models.JSONField(help_text='Example: {"description": "Journal description", "members": [{"name": "Ali", "role": "Editor", "image": "/media/ali.png"}]}', verbose_name='Member Data (JSON)')),
            ],
            options={
                'verbose_name': 'About Us Setting',
                'verbose_name_plural': 'About Us Settings',
            },
        ),
        migrations.CreateModel(
            name='CallForPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Call Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Call for Paper',
                'verbose_name_plural': 'Calls for Papers',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Journal Title')),
                ('volume', models.CharField(max_length=50, verbose_name='Volume / Issue')),
                ('abstract', models.TextField(verbose_name='Abstract / Description')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('cover_image', models.ImageField(upload_to='journal/releases/covers/', verbose_name='Cover Image')),
                ('pdf_file', models.FileField(upload_to='journal/releases/pdfs/', verbose_name='Journal PDF File')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('university', models.CharField(max_length=255, verbose_name='University')),
                ('major', models.CharField(max_length=255, verbose_name='Field of Study')),
                ('article_text', models.TextField(verbose_name='Article Text')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='journal/submissions/images/', verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='journal/submissions/images/', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='journal/submissions/images/', verbose_name='Image 3')),
                ('pdf_file', models.FileField(upload_to='journal/submissions/pdfs/', verbose_name='Article PDF File')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journal.callforpaper', verbose_name='Related Call')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
