# Generated by Django 5.2.1 on 2026-08-27 12:34

import django.core.validators
import django.db.models.deletion
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='aboutusconfig',
            name='data',
            field=models.JSONField(help_text='{"description": "...", "members": [{"name": "Ali", "role": "Editor"}]}'),
        ),
        migrations.AlterField(
            model_name='aboutusconfig',
            name='title',
            field=models.CharField(default='About Us Settings', max_length=100),
        ),
        migrations.AlterField(
            model_name='release',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='cover_image',
            field=models.ImageField(upload_to=journal.models.release_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='release',
            name='pdf_file',
            field=models.FileField(upload_to=journal.models.release_pdf_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='release',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='volume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='article_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journal.callforpaper'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='submission',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.submission_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.submission_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.submission_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='pdf_file',
            field=models.FileField(upload_to=journal.models.submission_pdf_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '09123456789'.", regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='university',
            field=models.CharField(max_length=255),
        ),
    ]
