# Generated by Django 5.2.1 on 2026-08-29 19:34

import django.core.validators
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_aboutusconfig_options_alter_release_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforpaper',
            name='rules',
            field=models.TextField(blank=True, help_text='Enter each rule on a new line.', verbose_name='Submission Rules'),
        ),
        migrations.AddField(
            model_name='submission',
            name='docx_file',
            field=models.FileField(default='hw4.docx', upload_to=journal.models.submission_docx_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx'])], verbose_name='Main Article (DOCX)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutusconfig',
            name='data',
            field=models.JSONField(help_text='{"description": "...", "members": [{"name": "Ali", "role": "Editor", "image": ""}]}'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='article_text',
            field=models.TextField(verbose_name='Abstract (HTML)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.submission_pdf_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Referenced Paper (PDF)'),
        ),
    ]
