# Generated by Django 5.2.1 on 2026-09-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_callforpaper_rules_submission_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callforpaper',
            name='end_date',
            field=models.DateTimeField(help_text='Note: Inserted time is in UTC. Frontend will convert it to local Iran time.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='callforpaper',
            name='rules',
            field=models.JSONField(blank=True, default=dict, help_text='Enter JSON format. Example: {"قوانین": ["قانون 1", "قانون 2"], "هدف": ["هدف 1"]}', null=True, verbose_name='Submission Rules'),
        ),
        migrations.AlterField(
            model_name='callforpaper',
            name='start_date',
            field=models.DateTimeField(help_text='Note: Inserted time is in UTC. Frontend will convert it to local Iran time.', verbose_name='Start Date'),
        ),
    ]
