# Generated by Django 5.2.1 on 2026-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_callforpaper_end_date_alter_callforpaper_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusconfig',
            name='data',
            field=models.JSONField(help_text='JSON format. Example: {"description": "...", "members": [...], "guidelines": [{"title": "...", "content": "..."}]}'),
        ),
        migrations.AlterField(
            model_name='aboutusconfig',
            name='title',
            field=models.CharField(default='About Us & Guidelines Settings', max_length=100),
        ),
    ]
