# Generated by Django 5.2.1 on 2025-07-24 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationenrollment',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_enrollment_record_link', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='presentationenrollment',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='events.presentation'),
        ),
        migrations.AddField(
            model_name='presentationenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presenters',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='events.presenter', verbose_name='Presenters'),
        ),
        migrations.AddField(
            model_name='solocompetition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Parent Event'),
        ),
        migrations.AddField(
            model_name='solocompetitionregistration',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_registration_record_link', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='solocompetitionregistration',
            name='solo_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.solocompetition'),
        ),
        migrations.AddField(
            model_name='solocompetitionregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_competition_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamcontent',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_submission', to='events.competitionteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='contentlike',
            name='team_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.teamcontent', verbose_name='Liked Content'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='team_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.teamcontent', verbose_name='Team Content'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='team_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.teamcontent', verbose_name='Commented Content'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.competitionteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('group_competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='presentationenrollment',
            unique_together={('user', 'presentation')},
        ),
        migrations.AlterUniqueTogether(
            name='solocompetitionregistration',
            unique_together={('user', 'solo_competition')},
        ),
        migrations.AlterUniqueTogether(
            name='contentlike',
            unique_together={('user', 'team_content')},
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user', 'team')},
        ),
    ]
