# Generated by Django 5.2.1 on 2025-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='type',
            field=models.CharField(choices=[('course', 'course'), ('talk', 'Talk'), ('workshop', 'Workshop')], default='talk', max_length=10, verbose_name='Type'),
        ),
    ]
