# Generated by Django 5.2.1 on 2025-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_presentation_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcompetition',
            name='price_per_group',
        ),
        migrations.AddField(
            model_name='groupcompetition',
            name='price_per_member',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price per Member (e.g., Toman)'),
        ),
    ]
