# Generated by Django 5.2.1 on 2025-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_solocompetitionregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Event ID'),
        ),
    ]
