# Generated by Django 5.2.1 on 2025-07-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_groupcompetition_allow_content_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/%Y/%m/', verbose_name='Event Poster'),
        ),
        migrations.AddField(
            model_name='groupcompetition',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='competition_posters/%Y/%m/', verbose_name='Competition Poster'),
        ),
        migrations.AddField(
            model_name='solocompetition',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='competition_posters/%Y/%m/', verbose_name='Competition Poster'),
        ),
    ]
