# Generated by Django 5.2.1 on 2025-09-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solocompetitionregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
