# Generated by Django 5.2.1 on 2025-08-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_presentation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationenrollment',
            name='certificate_requested',
            field=models.BooleanField(default=False),
        ),
    ]
