# Generated by Django 5.2.1 on 2025-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_groupcompetition_price_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12, verbose_name='Level'),
        ),
    ]
