# Generated by Django 5.2.1 on 2025-09-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_presentation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Prerequisites or materials participants should have/know.', verbose_name='Requirements'),
        ),
    ]
