# Generated by Django 5.2.1 on 2025-07-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionteam',
            name='member_emails_snapshot',
        ),
    ]
