# Generated by Django 5.2.1 on 2025-08-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_presentationenrollment_certificate_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationenrollment',
            name='certificate_requested',
        ),
    ]
