# Generated by Django 5.2.1 on 2025-08-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_presentationenrollment_certificate_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(default='AUT CE', max_length=255, verbose_name='Manager Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupcompetition',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Parent Event'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='events.event', verbose_name='Parent Event'),
        ),
        migrations.AlterField(
            model_name='solocompetition',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Parent Event'),
        ),
    ]
