# Generated by Django 5.2.1 on 2025-09-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_presentation_requirements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='government_id_picture',
        ),
        migrations.AddField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='group_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='events.groupcompetition', verbose_name='Parent Group Competition'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('pending_admin_verification', 'Pending Admin Verification'), ('rejected_by_admin', 'Rejected by Admin'), ('approved_awaiting_payment', 'Approved - Awaiting Payment'), ('in_cart', 'In Cart (Awaiting Checkout)'), ('awaiting_payment_confirmation', 'Awaiting Payment Confirmation'), ('payment_failed', 'Payment Failed'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='forming', max_length=40, verbose_name='Team Status'),
        ),
    ]
