# Generated by Django 5.2.1 on 2025-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_competitionteam_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='contents',
            field=models.TextField(blank=True, default='', help_text='Contents or materials discussed in the presentation.', verbose_name='Contents'),
        ),
    ]
