# Generated by Django 5.2.1 on 2025-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_manager_alter_groupcompetition_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['start_time', 'title'], 'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active for Registration?'),
        ),
    ]
