# Generated by Django 5.2.1 on 2025-10-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_presentation_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='timing',
            field=models.TextField(blank=True, default='', help_text="Presentation's timing", verbose_name='Timing'),
        ),
    ]
