# Generated by Django 5.2.1 on 2025-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_presentation_options_presentation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Event ID'),
        ),
    ]
