# Generated by Django 5.2.1 on 2025-09-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_presentation_options_presentation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='presentation_posters/%Y/%m/', verbose_name='Presentation Poster'),
        ),
    ]
