# Generated by Django 5.2.1 on 2026-09-27 19:52

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_presentation_timing'),
        ('shop', '0024_discountcode_multiple_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='teammembership',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=events.models.invitation_expiry, null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamcontent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_submissions', to='events.competitionteam', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='solocompetitionregistration',
            index=models.Index(fields=['solo_competition', 'status'], name='events_solo_solo_co_4591e5_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='events_team_user_id_47af07_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='events_team_team_id_0c5413_idx'),
        ),
        migrations.AddField(
            model_name='competitionregistrationmember',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.groupcompetition'),
        ),
        migrations.AddField(
            model_name='competitionregistrationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_rosters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionteamregistration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.groupcompetition'),
        ),
        migrations.AddField(
            model_name='competitionteamregistration',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_registration', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='competitionteamregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionteamregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.competitionteam'),
        ),
        migrations.AddField(
            model_name='competitionregistrationmember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.competitionteamregistration'),
        ),
        migrations.AddField(
            model_name='teamcontent',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_submission', to='events.competitionteamregistration'),
        ),
        migrations.AddIndex(
            model_name='competitionteamregistration',
            index=models.Index(fields=['competition', 'status'], name='events_comp_competi_b645ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitionteamregistration',
            constraint=models.UniqueConstraint(fields=('team', 'competition'), name='unique_team_competition'),
        ),
        migrations.AddConstraint(
            model_name='competitionregistrationmember',
            constraint=models.UniqueConstraint(fields=('registration', 'user'), name='unique_registration_member'),
        ),
        migrations.AddConstraint(
            model_name='competitionregistrationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('reserved', True)), fields=('competition', 'user'), name='unique_reserved_comp_member'),
        ),
    ]
