# Generated by Django 5.2.1 on 2026-09-27 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_backfill_team_registrations'),
        ('shop', '0025_team_registration_order_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitionteamregistration',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_approval', 'pending_payment', 'active', 'rejected', 'cancelled'])), name='valid_team_registration_status'),
        ),
        migrations.AddConstraint(
            model_name='competitionteamregistration',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='nonnegative_team_registration_price'),
        ),
    ]
