# Generated by Django 5.2.1 on 2026-10-05 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_registration_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_prerequisites', to='events.groupcompetition')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_prerequisites', to='events.presentation')),
                ('required_group_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_registrations', to='events.groupcompetition')),
                ('required_presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_registrations', to='events.presentation')),
                ('required_solo_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_registrations', to='events.solocompetition')),
                ('solo_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_prerequisites', to='events.solocompetition')),
            ],
            options={
                'verbose_name': 'Registration prerequisite',
                'verbose_name_plural': 'Registration prerequisites',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group_competition__isnull', True), ('presentation__isnull', False), ('solo_competition__isnull', True)), models.Q(('group_competition__isnull', True), ('presentation__isnull', True), ('solo_competition__isnull', False)), models.Q(('group_competition__isnull', False), ('presentation__isnull', True), ('solo_competition__isnull', True)), _connector='OR'), name='one_prerequisite_target'), models.CheckConstraint(condition=models.Q(models.Q(('required_group_competition__isnull', True), ('required_presentation__isnull', False), ('required_solo_competition__isnull', True)), models.Q(('required_group_competition__isnull', True), ('required_presentation__isnull', True), ('required_solo_competition__isnull', False)), models.Q(('required_group_competition__isnull', False), ('required_presentation__isnull', True), ('required_solo_competition__isnull', True)), _connector='OR'), name='one_prerequisite_requirement')],
            },
        ),
    ]
