# Generated by Django 5.2.1 on 2026-10-06 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registrationprerequisite'),
        ('shop', '0025_team_registration_order_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionteamregistration',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.RemoveConstraint(
            model_name='competitionteamregistration',
            name='unique_team_competition',
        ),
        migrations.AddConstraint(
            model_name='competitionteamregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'pending_payment', 'active', 'rejected'])), fields=('team', 'competition'), name='unique_non_cancelled_team_competition'),
        ),
    ]
