# Generated by Django 5.2.1 on 2025-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(help_text='HEX, e.g. #FF5733', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField()),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='job_logos/')),
                ('company_url', models.URLField(blank=True, null=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='jobs', to='jobs.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
