# Generated by Django 5.2.1 on 2025-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='job',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
