# Generated by Django 5.2.1 on 2026-08-29 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_rial', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='IRR', editable=False, max_length=3)),
                ('purpose', models.CharField(choices=[('order', 'Order'), ('wallet_top_up', 'Wallet top-up')], db_index=True, max_length=32)),
                ('reference_id', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires payment'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='requires_payment', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='settlement', serialize=False, to='payment_core.paymentintent')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending provider verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='created', max_length=16)),
                ('gateway_authority', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('gateway_reference_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payment_core.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['purpose', 'reference_id'], name='payment_cor_purpose_302923_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_rial__gt', 0)), name='payment_intent_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['intent', '-created_at'], name='payment_cor_intent__7b44c6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'gateway_authority'], name='payment_cor_provide_1e8b9a_idx'),
        ),
    ]
