# Generated by Django 5.2.1 on 2025-09-12 18:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=20, null=True, validators=[accounts.models.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
