# Generated by Django 5.2.1 on 2025-07-17 15:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=20, null=True, unique=True, validators=[accounts.models.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/', validators=[accounts.models.validate_image_size], verbose_name='Profile Picture'),
        ),
    ]
