# Generated by Django 5.2.1 on 2025-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Github_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
