# Generated by Django 5.2.1 on 2025-09-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
        ('accounts', '0003_staff_github_link_staff_team'),
    ]

    operations = [
    ]
