# Generated by Django 5.2.1 on 2025-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sky_password',
            field=models.CharField(blank=True, help_text='8-character password for online classes.', max_length=8, null=True, verbose_name='Online Class Password'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sky_username',
            field=models.CharField(blank=True, help_text='8-character unique username for online classes.', max_length=8, null=True, unique=True, verbose_name='Online Class Username'),
        ),
    ]
