# Generated by Django 5.2.1 on 2025-09-06 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cartitem_order_remove_cartitem_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_gateway_redirect', 'Awaiting Gateway Redirect'), ('payment_failed', 'Payment Failed'), ('verified', 'Verified'), ('completed', 'Completed')], default='pending', max_length=40)),
                ('payment_gateway_authority', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('payment_gateway_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('orders', models.ManyToManyField(related_name='batches', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
