# Generated by Django 5.2.1 on 2025-09-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0004_paymentbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_cart_items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reserved_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_cart_items', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved (in an unpaid/processing order)'), ('purchased', 'Purchased (paid & fulfilled)')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'content_type', 'object_id', 'status'], name='shop_cartit_cart_id_a114b5_idx'),
        ),
    ]
