# Generated by Django 5.2.1 on 2025-09-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_presentation_options_presentation_is_active'),
        ('shop', '0005_cartitem_reserved_order_cartitem_reserved_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='events.event'),
        ),
    ]
