# Generated by Django 5.2.1 on 2025-09-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_presentation_options_presentation_is_active'),
        ('shop', '0006_alter_cartitem_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='shop_cartit_cart_id_a114b5_idx',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_cart_items', to='events.event'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('owned', 'owned'), ('reserved', 'reserved')], default='owned', max_length=32),
        ),
    ]
