# Generated by Django 5.2.1 on 2025-09-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_cartitem_shop_cartit_cart_id_a114b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='event',
            field=models.ForeignKey(blank=True, help_text='If set, discount applies only to items of this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='events.event'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='If set, number of times a single user can redeem this code.', null=True),
        ),
    ]
