# Generated by Django 5.2.1 on 2025-09-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0009_discountredemption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'Discount Code', 'verbose_name_plural': 'Discount Codes'},
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='event',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='max_uses_per_user',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='value',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Discount target type'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount target object id'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Total times this code can be used across all users', null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='shop_discou_code_a62f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_discou_content_2e737d_idx'),
        ),
    ]
