# Generated by Django 5.2.1 on 2025-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_discountcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
