# Generated by Django 5.2.1 on 2025-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_discountcode_max_uses_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment App',
                'verbose_name_plural': 'Payment Apps',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='redirect_app',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='redirect_app',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
