# Generated by Django 5.2.1 on 2025-09-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_presentation_poster'),
        ('shop', '0012_paymentapp_order_redirect_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('features', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='events.event'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), models.Q(('app_label', 'shop'), ('model', 'product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), models.Q(('app_label', 'shop'), ('model', 'product')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Discount target type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), models.Q(('app_label', 'shop'), ('model', 'product')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'content_type', 'object_id')},
        ),
    ]
