# Generated by Django 5.2.1 on 2025-09-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_presentation_poster'),
        ('shop', '0013_product_order_event_alter_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='reserved_order',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='reserved_order_item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='events.event'),
        ),
    ]
