# Generated by Django 5.2.1 on 2025-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_cartitem_reserved_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited stock.', null=True),
        ),
    ]
