# Generated by Django 5.2.1 on 2025-09-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_presentation_poster'),
        ('shop', '0015_product_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart_items', to='events.event'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), models.Q(('app_label', 'shop'), ('model', 'product')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
    ]
