# Generated by Django 5.2.1 on 2025-09-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cartitem_event_alter_orderitem_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentBatch',
        ),
    ]
