# Generated by Django 5.2.1 on 2025-09-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_delete_paymentbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('awaiting_gateway_redirect', 'Awaiting Gateway Redirect'), ('payment_failed', 'Payment Failed'), ('processing_enrollment', 'Processing Enrollment/Registration'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('failed_by_new_link', 'Failed (New Link Issued)'), ('refund_failed', 'Refund Failed')], default='pending_payment', max_length=30, verbose_name='Order Status'),
        ),
    ]
