# Generated by Django 5.2.1 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_authority',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_txn_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='redirect_app',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_payment', 'Pending Payment'),
                    ('processing_enrollment', 'Processing Enrollment/Registration'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                    ('payment_failed', 'Payment Failed'),
                    ('refunded', 'Refunded'),
                ],
                default='pending_payment',
                max_length=30,
                verbose_name='Order Status',
            ),
        ),
    ]
