# Generated by Django 5.2.1 on 2026-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_legacy_payment_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment App',
                'verbose_name_plural': 'Payment Apps',
            },
        ),
    ]
