# Generated by Django 5.2.1 on 2026-09-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0008_presentation_timing'),
        ('shop', '0021_paymentapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='parent_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_components', to='shop.orderitem', verbose_name='Parent pack order item'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'shop'), ('model', 'product')), models.Q(('app_label', 'shop'), ('model', 'pack')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'shop'), ('model', 'product')), models.Q(('app_label', 'shop'), ('model', 'pack')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Discount target type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'events'), ('model', 'competitionteam')), models.Q(('app_label', 'shop'), ('model', 'product')), models.Q(('app_label', 'shop'), ('model', 'pack')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type'),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Item ID')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'events'), ('model', 'presentation')), models.Q(('app_label', 'events'), ('model', 'solocompetition')), models.Q(('app_label', 'shop'), ('model', 'product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Item Type')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.pack')),
            ],
            options={
                'verbose_name': 'Pack Item',
                'verbose_name_plural': 'Pack Items',
                'ordering': ['pk'],
                'unique_together': {('pack', 'content_type', 'object_id')},
            },
        ),
    ]
