# Generated by Django 5.2.1 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_orderitem_parent_pack_alter_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='bypass_item_time_limits',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Allow this pack to be purchased after a contained item's registration "
                    'time has passed. Availability, capacity, ownership, and overlap checks still apply.'
                ),
                verbose_name='Bypass contained item time limits',
            ),
        ),
    ]
