# Generated by Django 5.2.1 on 2025-08-13 20:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_alter_presentation_options_presentation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('name_on_certificate', models.CharField(max_length=255)),
                ('file_en', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('file_fa', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.PositiveIntegerField(blank=True, help_text='Grade from 0 to 100 (only for courses)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.presentationenrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
