# Generated by Django 5.2.1 on 2025-07-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='events.presentationenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='certificaterequest',
            unique_together={('enrollment',)},
        ),
    ]
