# Generated by Django 5.2.1 on 2025-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
