# Generated by Django 5.2.1 on 2025-07-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_initial'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_certificate', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.presentationenrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.DeleteModel(
            name='CertificateRequest',
        ),
    ]
