# Generated by Django 5.2.1 on 2026-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Records error details if certificate rendering fails.', null=True, verbose_name='Generation Error'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Generation Status'),
        ),
        migrations.AddField(
            model_name='competitioncertificate',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Records error details if certificate rendering fails.', null=True, verbose_name='Generation Error'),
        ),
        migrations.AddField(
            model_name='competitioncertificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Generation Status'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Verified by Admin?'),
        ),
        migrations.AlterField(
            model_name='competitioncertificate',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Verified by Admin?'),
        ),
    ]
