# Generated by Django 5.2.1 on 2025-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncertificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
