# Generated by Django 5.2.1 on 2025-08-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_delete_certificaterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='file',
            new_name='file_en',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file_fa',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/'),
        ),
    ]
