# Generated by Django 5.2.1 on 2025-08-10 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.PositiveIntegerField(blank=True, help_text='Grade from 0 to 100 (only for courses)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
