# Generated by Django 5.2.1 on 2026-08-19 23:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0019_alter_cartitem_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cached balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_gateway', 'Awaiting Gateway'), ('credited', 'Credited'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('gateway_authority', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('gateway_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Top-up',
                'verbose_name_plural': 'Wallet Top-ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('topup', 'Top-up'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Actor for administrative adjustments and refunds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='shop.order')),
                ('related_entry', models.ForeignKey(blank=True, help_text='Original debit that this refund compensates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_entries', to='wallet.walletentry')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.wallet')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.wallettopup')),
            ],
            options={
                'verbose_name': 'Wallet Ledger Entry',
                'verbose_name_plural': 'Wallet Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallettopup',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_topup_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__006c46_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['entry_type', 'order'], name='wallet_wall_entry_t_4666f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'debit'), ('entry_type', 'purchase'), ('order__isnull', False)), fields=('order',), name='unique_wallet_purchase_per_order'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'refund'), ('related_entry__isnull', False)), fields=('related_entry',), name='unique_wallet_refund_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'topup'), ('topup__isnull', False)), fields=('topup',), name='unique_wallet_credit_per_topup'),
        ),
    ]
