# Generated by Django 5.2.1 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_legacy_payment_schema'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='wallet',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.RemoveField(
            model_name='wallettopup',
            name='idempotency_key',
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='order',
            field=models.ForeignKey(
                blank=True,
                help_text='Order to pay after this top-up is verified, if any.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='wallet_topups',
                to='shop.order',
            ),
        ),
        migrations.AlterField(
            model_name='wallettopup',
            name='gateway_authority',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettopup',
            name='wallet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='topups',
                to='wallet.wallet',
            ),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='wallet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='entries',
                to='wallet.wallet',
            ),
        ),
    ]
