# Generated by Django 5.2.1 on 2026-08-29 20:11

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_core(apps, schema_editor):
    PaymentAttempt = apps.get_model('payment_core', 'PaymentAttempt')
    PaymentIntent = apps.get_model('payment_core', 'PaymentIntent')
    PaymentSettlement = apps.get_model('payment_core', 'PaymentSettlement')
    WalletTopUp = apps.get_model('wallet', 'WalletTopUp')

    used_references = set(
        PaymentAttempt.objects.exclude(gateway_reference_id__isnull=True)
        .values_list('gateway_reference_id', flat=True)
    )
    for topup in WalletTopUp.objects.select_related('wallet').iterator():
        amount_rial = int(topup.amount * 10)
        if topup.status == 'credited':
            intent_status = 'succeeded'
            attempt_status = 'verified'
        elif topup.status == 'awaiting_gateway':
            intent_status = 'processing'
            attempt_status = 'pending'
        elif topup.status in {'failed', 'cancelled'}:
            intent_status = 'failed'
            attempt_status = 'failed'
        else:
            intent_status = 'requires_payment'
            attempt_status = 'created'

        intent = PaymentIntent.objects.create(
            user_id=topup.wallet.user_id,
            amount_rial=max(amount_rial, 1),
            purpose='wallet_top_up',
            reference_id=str(topup.public_id),
            description=f'Legacy wallet top-up {topup.public_id}',
            idempotency_key=f'wallet-topup-intent:{topup.public_id}',
            status=intent_status,
            metadata={'source': 'wallet_migration'},
            succeeded_at=topup.credited_at if intent_status == 'succeeded' else None,
        )
        reference = topup.gateway_ref_id
        if reference in used_references:
            reference = None
        elif reference:
            used_references.add(reference)
        attempt = PaymentAttempt.objects.create(
            intent=intent,
            provider='zarinpal',
            idempotency_key=f'wallet-topup-attempt:{topup.public_id}',
            status=attempt_status,
            gateway_authority=topup.gateway_authority,
            gateway_reference_id=reference,
            payment_url=topup.payment_url,
            error_code='legacy_payment_failed' if attempt_status == 'failed' else '',
            provider_data={'source': 'wallet_migration'},
            verified_at=topup.credited_at if attempt_status == 'verified' else None,
        )
        WalletTopUp.objects.filter(pk=topup.pk).update(
            payment_intent_id=intent.pk,
            payment_attempt_id=attempt.pk,
        )
        if topup.status == 'credited':
            PaymentSettlement.objects.create(
                intent=intent,
                idempotency_key=f'payment-settlement:{intent.pk}',
                status='succeeded',
                settled_at=topup.credited_at,
            )


def remove_backfilled_payment_core(apps, schema_editor):
    PaymentAttempt = apps.get_model('payment_core', 'PaymentAttempt')
    PaymentIntent = apps.get_model('payment_core', 'PaymentIntent')
    PaymentSettlement = apps.get_model('payment_core', 'PaymentSettlement')
    WalletTopUp = apps.get_model('wallet', 'WalletTopUp')

    intent_ids = list(
        PaymentIntent.objects.filter(idempotency_key__startswith='wallet-topup-intent:')
        .values_list('pk', flat=True)
    )
    WalletTopUp.objects.filter(payment_intent_id__in=intent_ids).update(
        payment_intent_id=None,
        payment_attempt_id=None,
    )
    PaymentSettlement.objects.filter(intent_id__in=intent_ids).delete()
    PaymentAttempt.objects.filter(intent_id__in=intent_ids).delete()
    PaymentIntent.objects.filter(pk__in=intent_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_core', '0001_initial'),
        ('wallet', '0002_wallet_payment_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettopup',
            name='payment_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topup', to='payment_core.paymentattempt'),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='payment_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topup', to='payment_core.paymentintent'),
        ),
        migrations.RunPython(backfill_payment_core, remove_backfilled_payment_core),
    ]
